### ISSUE TITLE
renderer method

### ISSUE THREAD

**Issue by jegj** [rebelstackio/fluxable#3]
Why the method is called renderer instead of just "render" ?

https://github.com/rebelstackio/fluxable/blob/develop/lib/viewController.js#L6

**Comment by pablolimo** [comment]
To not confuse it with react's render method, now there is defineLayout instead.

**Comment by jegj** [comment]
so what will be all the methods related with layout and componets html ?

- renderer
- defineLayout 

???

**Comment by pablolimo** [comment]
Just defineLayout, renderer is internal, an example would be this:

`class MyComponent extends ViewController {
  defineLayout() {
    this.message = document.createElement('div');
    this.message.textContent = 'Hello World';
    this.content.appendChild(this.message);
  }
}`

**Comment by jegj** [comment]
nice!

**Comment by jegj** [comment]
we shouldm add README file about the documentation
