### ISSUE TITLE
Metashadow component Bug

### ISSUE THREAD

**Issue by oreyes1991** [rebelstackio/fluxable#32]
Let's say I want to create a static project without using webpack.
in my case, in my index.html I use jsdelivr to get the npm package as CDN
```html
<script src="https://cdn.jsdelivr.net/npm/@rebelstack-io/metaflux@1.1.2/dist/metaflux.js"></script>
```
and get a script type module, the same as the browser_test folder in this repository
but my shadow component doesn't display the initial state. Or the state changes
![image](https://user-images.githubusercontent.com/45575102/76898621-12398800-6864-11ea-9ba8-bd1172b8254d.png)

in the developer console, I have an error that says
```
Uncaught TypeError: Cannot read property 'getState' of undefined
```

in my constructor, I set the super to the store
```js
constructor () {
		super(window.storage);
		this.styles = [
			'css/general.css'
		];
	}
```
but the handleStoreEvents method isn't listening to the events, and  this.storage is undefined.

if I use window.storage.on method instead of handleStoreEvents and window.storage instead of this.storage. The component works as intended

**Comment by pablolimo** [comment]
https://cdn.jsdelivr.net/npm/@rebelstack-io/metaflux@1.1.3/dist/metaflux.js

Fixed
